### ISSUE TITLE
Fire CMake configure fails when MAGMA not available

### ISSUE THREAD

**Issue by amccaskey** [jayjaybillings/fire#11]
Running CMake 3.6.2 (which is the default now in Fedora 25 when you run dnf install cmake) fails with 

```bash
-- MAGMA support requested. Searching at MAGMA_ROOT=.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'magma;magma_sparse'
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:646 (message):
  None of the required 'magma;magma_sparse' found
Call Stack (most recent call first):
  cmake/Modules/FindMAGMA.cmake:61 (pkg_search_module)
  solvers/CMakeLists.txt:54 (find_package)
```

when the user does not have MAGMA installed. Later versions of CMake prefer 

```cpp
if (MAGMA_ROOT) (works for 3.6.2)
```
instead of 
```cpp
if (NOT MAGMA_ROOT STREQUAL "") (does not work for 3.6.2)
```

**Comment by jayjaybillings** [comment]
Does the former work for versions less than 3.6.2?

**Comment by amccaskey** [comment]
Former works with 3.4.3 and 2.8.2. Latter fails for 2.8.2 and 3.4.3.

**Comment by jayjaybillings** [comment]
I switched it to the former.

N.B. - I originally implemented it using the former method, but switched to the latter after I encountered some problems. Maybe those problems were symptoms of other things and this will work fine, but it is important to note that it didn't initially work correctly.
