### ISSUE TITLE
Add Fire Tensor Jekyll Post

### ISSUE THREAD

**Issue by amccaskey** [jayjaybillings/fire#14]
Add a markdown document discussing the architecture and use Fire's new Tensor support.

**Comment by jayjaybillings** [comment]
+1. Also, we should regenerate the doxygen documentation so that the tensor API shows up at 

http://www.jayjaybillings.com/fire/api/html/

**Comment by jayjaybillings** [comment]
I haven't figured out how to automate that yet. :-(

**Comment by amccaskey** [comment]
That sounds good to me. Do we just have to run make doc, then upload the result somewhere?

**Comment by jayjaybillings** [comment]
Yes. Just copy the output of the html and latex doc directories to ${CMAKE_SOURCE_DIR}/docs/api.

**Comment by amccaskey** [comment]
Interesting thought - add_custom_target lets you specify a second command. We could set that second command to copy the results to docs/api... then push it or something??? *thinking out loud*

**Comment by jayjaybillings** [comment]
Yes, something like that. I'm currently too lazy to investigate it though, so have at it! ;-)

**Comment by jayjaybillings** [comment]
Tensors have been deleted.
