### ISSUE TITLE
Remove Eclipse .cproject and .project files

### ISSUE THREAD

**Issue by amccaskey** [jayjaybillings/fire#16]
These files can and usually do contain information that is specific to the users Eclipse workspace, making them not very portable and always show up as changed files in the Git Staging view. 

I propose we remove them from the repo. Any objections @jayjaybillings ?

**Comment by jayjaybillings** [comment]
I don't see any .project or .cproject files, just a .pydevproject file, which we should delete... did you already remove them? I noticed they are in .gitignore now.

I'm closing this since I suspect your answer is yes.
