### ISSUE TITLE
Add Travis Docker CI

### ISSUE THREAD

**Issue by amccaskey** [jayjaybillings/fire#18]
@jayjaybillings 

When you get a chance, will you go into the Settings > Integration and Services and add Travis CI as a service for this project? I just made a commit that will set that up to run a build and test on Fedora 25 and Ubuntu 16.04 every time we push to master.

**Comment by jayjaybillings** [comment]
Done. I don't have a Travis user account and stuff so I didn't configure that. Let me know if you need additional changes.
